namespace BlogModels.Models;

/// <summary>
/// Represents a single persisted site-wide configuration entry.
/// </summary>
/// <remarks>
/// <para><b>Purpose:</b> Row-level representation of the <c>SiteSetting</c> table. Site
/// configuration is stored as key/value pairs rather than one wide row so new settings can be
/// added without a schema migration.</para>
///
/// <para><b>Code Flow:</b></para>
/// <list type="number">
///   <item><c>SiteSettingRepo</c> materialises these rows from PostgreSQL via Dapper.</item>
///   <item><c>SiteSettingsService</c> projects the rows into the strongly typed
///     <see cref="SiteSettings"/> aggregate and caches the result.</item>
///   <item>Saving reverses the projection and upserts one row per key.</item>
/// </list>
///
/// <para><b>Dependencies:</b> None in code — this is a plain contract in the dependency leaf
/// project. In the schema: the <c>SiteSetting</c> table created by
/// <c>PostgresScripts/016-SiteSettings.sql</c>.</para>
///
/// <para><b>Usage:</b> Prefer <see cref="SiteSettings"/> in application code; work with this
/// type only when reading or writing an individual key. An instance obtained from the repository
/// still holds the <i>encrypted</i> value when <see cref="IsSecret"/> is set — only the service
/// decrypts — so never render <see cref="SettingValue"/> straight from a repository result.</para>
///
/// <para><b>Encryption at rest:</b> exactly two keys are secret — <c>SmtpPassword</c> and
/// <c>StorageCloudAccessKey</c>, listed on <c>SiteSettingsMapper.SecretKeys</c>. Their values are
/// AES-encrypted by <c>AppEncrypt</c> on write and decrypted on read, under the single key supplied
/// as the <c>AppEncryptionKey</c> configuration value (<see cref="AppSecrets.EncryptionKeyPath"/>).
/// There is no key versioning and no key identifier stored beside the ciphertext, so
/// <b>rotating that key makes every already-encrypted row permanently undecryptable</b> — the
/// stored SMTP password and cloud access key are lost, not merely inaccessible, and must be
/// re-entered through the Settings screen after any rotation.</para>
/// </remarks>
public class SiteSetting
{
    /// <summary>
    /// Surrogate primary key generated by the database. Not the identity of the setting — that is
    /// <see cref="SettingKey"/>, which is what the upsert matches on, so a row's id can change
    /// while the setting it carries does not.
    /// </summary>
    public long SettingId { get; set; }

    /// <summary>
    /// The setting's identity: a unique key drawn from the constants on <c>SiteSettingKeys</c>.
    /// Matched with <c>StringComparer.Ordinal</c> throughout, so it is case- and
    /// whitespace-sensitive; a key that differs by one character is not "the same setting spelled
    /// differently" but a new, unread row, and the aggregate silently keeps its built-in default.
    /// </summary>
    public string SettingKey { get; set; } = string.Empty;

    /// <summary>
    /// The stored value, always as text regardless of the property it projects onto — typed
    /// conversion (int, bool) happens in <c>SiteSettingsMapper</c>, which falls back to the default
    /// rather than throwing when a value will not parse.
    /// </summary>
    /// <remarks>
    /// When <see cref="IsSecret"/> is set, this holds AES <i>ciphertext</i> at the repository
    /// boundary and plaintext only after <c>SiteSettingsService</c> has decrypted it. The direction
    /// matters: a value assigned here on the way to a save is expected to be plaintext and will be
    /// encrypted for you, while a value read back from the repository has not been decrypted yet.
    /// Confusing the two double-encrypts the credential or writes it to the database in the clear.
    /// </remarks>
    public string SettingValue { get; set; } = string.Empty;

    /// <summary>
    /// Logical grouping that decides which tab of the admin Settings screen the key appears on
    /// (General, Blog, Seo, Social, Theme, Smtp, Storage). Presentation only — nothing authorises
    /// or validates on it, and a misfiled group hides a setting from the UI without affecting the
    /// value the application reads.
    /// </summary>
    public string SettingGroup { get; set; } = string.Empty;

    /// <summary>
    /// Whether this row's value is encrypted at rest. Derived from the key, not stored independently
    /// — the service recomputes it from <c>SiteSettingsMapper.IsSecretKey</c> on every write, so the
    /// column is a description of the key rather than a switch a caller can flip.
    /// </summary>
    /// <remarks>
    /// True for exactly two keys today: <c>SmtpPassword</c> and <c>StorageCloudAccessKey</c>.
    /// Adding a key to <c>SecretKeys</c> encrypts it from that point on but does not retroactively
    /// encrypt rows already written in the clear; removing one leaves existing ciphertext that
    /// nothing will decrypt. Either change needs a data migration, not just a list edit.
    /// </remarks>
    public bool IsSecret { get; set; }

    /// <summary>
    /// When the row was last written. Surfaced as <see cref="SiteSettings.UpdatedOn"/> so callers
    /// can tell a configured site from one still running on built-in defaults; it is not a cache
    /// key — the service invalidates its cache on save rather than comparing timestamps.
    /// </summary>
    public DateTime UpdatedOn { get; set; }
}
